name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 3 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: EStog/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_languages: yes
          plugin_languages_limit: 0
          plugin_languages_categories: data, markup, programming, prose
          config_order: base.header, languages
